# Generated by Django 5.0.4 on 2024-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wanted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_action', models.CharField(max_length=10, null=True)),
                ('property_type', models.CharField(default=None, max_length=20)),
                ('property_subtypes', models.CharField(default=None, max_length=20)),
                ('city_name', models.CharField(choices=[('isl', 'Islamabad'), ('lhr', 'Lahore'), ('swl', 'Sahiwal'), ('psh', 'Peshawar'), ('kar', 'Karachi')], max_length=100)),
                ('area_name', models.CharField(choices=[('main', 'Islamabad-main'), ('main2', 'Islamabad-outskirts'), ('main', 'Lahore-main'), ('main2', 'Lahore-outskirts'), ('main', 'Sahiwal-main'), ('main2', 'Sahiwal-outskirts'), ('main', 'Peshawar-main'), ('main2', 'Peshawar-outskirts'), ('main', 'Karachi-main'), ('main2', 'Karachi-outskirts')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('additional_details', models.TextField()),
            ],
        ),
    ]
