# Generated by Django 5.0.4 on 2024-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='area_name',
            field=models.CharField(choices=[('main', 'Islamabad'), ('main2', 'Islamabad'), ('main', 'Lahore'), ('main2', 'Lahore'), ('main', 'Sahiwal'), ('main2', 'Sahiwal'), ('main', 'Peshawar'), ('main2', 'Peshawar'), ('main', 'Karachi'), ('main2', 'Karachi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='property_action',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
