# Generated by Django 5.0.4 on 2024-05-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_add_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPanel',
        ),
    ]
