# Generated by Django 5.0.4 on 2024-05-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_adminpanel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmessage',
            old_name='image',
            new_name='images',
        ),
    ]
