# Generated by Django 5.0.4 on 2024-05-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_rename_images_investmessage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmessage',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
